<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PNVD013" failures="1" tests="6" name="selenium.webdriver1.Assignment_03_Xpath" time="24.418" errors="0" timestamp="08 Jan 2022 03:25:01 GMT" skipped="0">
  <testcase classname="selenium.webdriver1.Assignment_03_Xpath" name="TC_04_Register_Password_Less_Than_6_Chars" time="2.900"/>
  <testcase classname="selenium.webdriver1.Assignment_03_Xpath" name="TC_01_Register_Empty_Data" time="7.016"/>
  <testcase classname="selenium.webdriver1.Assignment_03_Xpath" name="TC_05_Register_Incorrect_Password" time="5.056">
    <failure message="expected [Mật khẩu nhập lại không khớp] but found [Mật khẩu bạn nhập không khớp]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Mật khẩu nhập lại không khớp] but found [Mật khẩu bạn nhập không khớp]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at selenium.webdriver1.Assignment_03_Xpath.TC_05_Register_Incorrect_Password(Assignment_03_Xpath.java:130)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_05_Register_Incorrect_Password -->
  <testcase classname="selenium.webdriver1.Assignment_03_Xpath" name="TC_06_Register_Invalid_Phone" time="3.603"/>
  <testcase classname="selenium.webdriver1.Assignment_03_Xpath" name="TC_03_Register_Incorrect_Email" time="2.917"/>
  <testcase classname="selenium.webdriver1.Assignment_03_Xpath" name="TC_02_Register_Invalid_Email" time="2.926"/>
</testsuite> <!-- selenium.webdriver1.Assignment_03_Xpath -->
